import { ReactNode } from 'react'
import Head from 'next/head'
import Header from './header'
import Footer from './footer'
import Main from './main'
import styles from "../styles/components/layout.module.scss";

type Props = {
  children?: ReactNode
  home?: Boolean
}

export default function Layout({ children, home }: Props) {
  return (
    <div className={styles.body}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.body__main}>
        <Header />

        <Main>{children}</Main>

        <Footer>フッター</Footer>
      </div>
    </div>
  )
}
